In [2]:
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
avg_exec_times_file = "./data/recorded_average_exec_times.csv"

avg_df = pd.read_csv(avg_exec_times_file)
avg_df.head()

       modulo   comment  unidade  round
0  fluxograma  original     3843  1.543
1  fluxograma  original     7433  1.998
2  fluxograma  original     8380  1.701
3  fluxograma  original    13325  1.283
4  fluxograma  original    14009  0.396

In [11]:
fluxograma_avg_df = avg_df[avg_df['modulo'] == 'fluxograma']
corregedoria_avg_df = avg_df[avg_df['modulo'] == 'corregedoria']

In [9]:
fluxograma_avg_df[fluxograma_avg_df['comment'] == "original"].head(15)

        modulo   comment  unidade  round
0   fluxograma  original     3843  1.543
1   fluxograma  original     7433  1.998
2   fluxograma  original     8380  1.701
3   fluxograma  original    13325  1.283
4   fluxograma  original    14009  0.396
5   fluxograma  original    14013  0.294
6   fluxograma  original    17384  1.325
7   fluxograma  original    18007  0.356
8   fluxograma  original    18104  1.909
9   fluxograma  original    18228  0.877
10  fluxograma  original    44508  6.738

In [10]:
fluxograma_avg_df[fluxograma_avg_df['comment'] == "optimized"].head(15)

        modulo    comment  unidade  round
11  fluxograma  optimized     3843  0.188
12  fluxograma  optimized     7433  0.260
13  fluxograma  optimized     8380  0.215
14  fluxograma  optimized    13325  0.170
15  fluxograma  optimized    14009  0.045
16  fluxograma  optimized    14013  0.033
17  fluxograma  optimized    17384  0.200
18  fluxograma  optimized    18007  0.040
19  fluxograma  optimized    18104  0.241
20  fluxograma  optimized    18228  0.115
21  fluxograma  optimized    44508  0.544

In [12]:
corregedoria_avg_df[corregedoria_avg_df['comment'] == "original"].head(15)

          modulo   comment  unidade  round
22  corregedoria  original     3843  1.558
23  corregedoria  original     7433  2.025
24  corregedoria  original     8380  1.811
25  corregedoria  original    13325  1.273
26  corregedoria  original    14009  0.399
27  corregedoria  original    14013  0.303
28  corregedoria  original    17384  1.313
29  corregedoria  original    18007  0.351
30  corregedoria  original    18104  1.958
31  corregedoria  original    18228  0.867
32  corregedoria  original    44508  6.776

In [13]:
corregedoria_avg_df[corregedoria_avg_df['comment'] == "optimized"].head(15)

          modulo    comment  unidade  round
33  corregedoria  optimized     3843  0.195
34  corregedoria  optimized     7433  0.254
35  corregedoria  optimized     8380  0.225
36  corregedoria  optimized    13325  0.182
37  corregedoria  optimized    14009  0.046
38  corregedoria  optimized    14013  0.033
39  corregedoria  optimized    17384  0.160
40  corregedoria  optimized    18007  0.038
41  corregedoria  optimized    18104  0.246
42  corregedoria  optimized    18228  0.118
43  corregedoria  optimized    44508  0.546